### ISSUE TITLE
Problems updating existing app to use library

### ISSUE THREAD

**Issue by johnwargo** [ControlEverythingCom/Fob_Alarm#2]
I'm updating an existing project, and when I compile the sketch, I get the following:

```
garage_door_with_code_shield_fob.ino:23:1: 'KeyFob' does not name a type 
garage_door_with_code_shield_fob.ino:85:9: 'fob' was not declared in this scope
```

Any idea why I'm getting this issue?

**Comment by telliottosceola** [comment]
Hi John,

Are you writing your code on Particle's WEB IDE?  If so can you share the code?  I'd be happy to take a look.  Sounds to me like KeyFob.h is not being included.

**Comment by johnwargo** [comment]
Yeah, I am. I added the library to the project and confirmed it's there. how do you want me to share it with you?

**Comment by johnwargo** [comment]
![particle-ide](https://user-images.githubusercontent.com/571463/42543394-ae42bbb6-8479-11e8-9e5a-28072e739429.png)

**Comment by johnwargo** [comment]
deleted source

**Comment by telliottosceola** [comment]
Hi John,

Honestly that library was a little old and I did not exactly know how to post Particle libraries at the time.  Delete 
`#include <Fob_Alarm.h`
and replace it with:
`#include <KeyFob.h>`
Let me know if that does not resolve the problem.

**Comment by johnwargo** [comment]
OK, but when I look at the source for the library, KeyFob.h has nothing in it.

**Comment by johnwargo** [comment]
hmmm, OK, that worked (I think). Let me deploy it and test
